package br.com.mineradortimemania.app;
import java.util.*;
public final class MiningEngine{
 public interface Progress{void onProgress(int p,String s);}
 static int ov(int[]a,int[]b){int c=0;for(int x:a)for(int y:b)if(x==y){c++;break;}return c;}
 static String fmt(int[]a){StringBuilder s=new StringBuilder();for(int x:a){if(s.length()>0)s.append(" ");s.append(String.format("%02d",x));}return s.toString();}
 static int cycle(ArrayList<TimemaniaParser.Draw>d){boolean[]s=new boolean[81];int c=0,st=d.size()-1;for(int i=d.size()-1;i>=0;i--){st=i;for(int n:d.get(i).n)if(!s[n]){s[n]=true;c++;}if(c==80)break;}return st;}
 public static String general(ArrayList<TimemaniaParser.Draw>d){int cs=cycle(d);int[]f=new int[81],r=new int[81],cy=new int[81];for(int i=0;i<d.size();i++)for(int n:d.get(i).n){f[n]++;if(i>=d.size()-10)r[n]++;if(i>=cs)cy[n]++;}ArrayList<Integer>a=new ArrayList<>();for(int n=1;n<=80;n++)a.add(n);a.sort((x,y)->Integer.compare(f[y]+r[y]*8+cy[y]*5,f[x]+r[x]*8+cy[x]*5));int[]g=new int[10];for(int i=0;i<10;i++)g[i]=a.get(i);Arrays.sort(g);return "MÓDULO 1 — MINERADOR GERAL FUTURO\n\nJogo futuro de 10: "+fmt(g)+"\nCritérios: histórico + últimos 10 + ciclo.";}
 public static String pairs(ArrayList<TimemaniaParser.Draw>d,Progress p){int[][]cnt=new int[81][81];for(var x:d)for(int i=0;i<7;i++)for(int j=i+1;j<7;j++)cnt[x.n[i]][x.n[j]]++;class P{int a,b,c;P(int a,int b,int c){this.a=a;this.b=b;this.c=c;}}ArrayList<P>ps=new ArrayList<>();for(int a=1;a<=80;a++)for(int b=a+1;b<=80;b++)ps.add(new P(a,b,cnt[a][b]));ps.sort((x,y)->y.c-x.c);long best=-1;int[]core=null;int lim=140;
  for(int i=0;i<lim;i++)for(int j=i+1;j<lim;j++){P x=ps.get(i),y=ps.get(j);for(int k=j+1;k<lim;k++){P z=ps.get(k);TreeSet<Integer>s=new TreeSet<>(Arrays.asList(x.a,x.b,y.a,y.b,z.a,z.b));if(s.size()!=6)continue;int[]g=new int[6];int q=0;for(int n:s)g[q++]=n;int mx=0,q4=0,q5=0,q6=0;for(var dr:d){int o=ov(g,dr.n);mx=Math.max(mx,o);if(o>=4)q4++;if(o>=5)q5++;if(o>=6)q6++;}if(mx<4)continue;long sc=q6*1000000000L+q5*100000000L+q4*1000000L+(x.c+y.c+z.c)*1000L;if(sc>best){best=sc;core=g;}}if(p!=null&&i%10==0)p.onProgress(i*70/lim,"Analisando três duplas populares");}
  if(core==null)throw new IllegalStateException("Nenhum núcleo encontrado.");TreeSet<Integer>s=new TreeSet<>();for(int n:core)s.add(n);int cs=cycle(d);int[]f=new int[81],r=new int[81],cy=new int[81];for(int i=0;i<d.size();i++)for(int n:d.get(i).n){f[n]++;if(i>=d.size()-10)r[n]++;if(i>=cs)cy[n]++;}ArrayList<Integer>a=new ArrayList<>();for(int n=1;n<=80;n++)if(!s.contains(n))a.add(n);a.sort((x,y)->Integer.compare(f[y]+r[y]*8+cy[y]*5,f[x]+r[x]*8+cy[x]*5));for(int i=0;i<4;i++)s.add(a.get(i));int[]g=new int[10];int q=0;for(int n:s)g[q++]=n;return "MÓDULO 2 — 3 DUPLAS POPULARES\n\nNúcleo de 6: "+fmt(core)+"\nJogo futuro de 10: "+fmt(g)+"\nO núcleo exige no mínimo uma quadra histórica; quina e 6 acertos recebem prioridade.";}
 public static int[]parse(String x){TreeSet<Integer>s=new TreeSet<>();for(String q:x.split("[^0-9]+"))if(!q.isEmpty()){int n=Integer.parseInt(q);if(n>=1&&n<=80)s.add(n);}int[]o=new int[s.size()];int i=0;for(int n:s)o[i++]=n;return o;}
 public static String group(ArrayList<TimemaniaParser.Draw>d,int[]pool){if(pool.length<10||pool.length>40)throw new IllegalArgumentException("Digite de 10 a 40 dezenas.");int cs=cycle(d);Integer[]a=new Integer[pool.length];for(int i=0;i<pool.length;i++)a[i]=pool[i];Arrays.sort(a,(x,y)->{int sx=0,sy=0;for(int i=0;i<d.size();i++){if(ov(new int[]{x},d.get(i).n)>0)sx+=1+(i>=d.size()-10?8:0)+(i>=cs?5:0);if(ov(new int[]{y},d.get(i).n)>0)sy+=1+(i>=d.size()-10?8:0)+(i>=cs?5:0);}return sy-sx;});int[]g=new int[10];for(int i=0;i<10;i++)g[i]=a[i];Arrays.sort(g);return "MÓDULO 3 — MINERADOR DE GRUPO\n\nGrupo: "+fmt(pool)+"\nJogo futuro de 10: "+fmt(g);}
}